"""Add content_items table

Revision ID: 4bd8cd1f8ec7
Revises: 56afc8db4b50
Create Date: 2026-02-03 10:14:46.413011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bd8cd1f8ec7"
down_revision: Union[str, None] = "56afc8db4b50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_items",
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("content_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("source_ref", sa.String(length=2048), nullable=True),
        sa.Column("storage_path", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("content_id"),
    )
    op.create_index(
        "idx_content_session_id", "content_items", ["session_id"], unique=False
    )
    op.create_index("idx_content_status", "content_items", ["status"], unique=False)
    op.create_index("idx_content_type", "content_items", ["content_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_content_type", table_name="content_items")
    op.drop_index("idx_content_status", table_name="content_items")
    op.drop_index("idx_content_session_id", table_name="content_items")
    op.drop_table("content_items")
    # ### end Alembic commands ###
